name: aflw
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - imageio
  - pip
  - python=3.6
  - tensorboard=1.12.0
  - tensorflow-gpu=1.12.0
  - numpy
  - pytorch=0.4.1
  - tabulate
  - torchvision
  - tqdm
  - pip:
    - tensorboardx
